Added functionality to job postings save/unsave button
zafrinn/CPS714-project pull request #31
Opened 2023-11-20 18:27 UTC by Edward-Boguslavsky

When clicking the save/unsave button, the front end now talks to the database and stores/removes the saved posting information under the selected user.

Note: When the postings/saved tabs are clicked on the job postings page, the saved postings are not updated unless the whole page is refreshed first. Nikki and I are actively trying to fix this

2023-11-21 01:30 UTC, nikkikapadia requested changes
plz only post PRs when you have the full functionality; implement the list updating first and then I can review it.

2023-11-24 17:41 UTC, Edward-Boguslavsky commented
@nikkikapadia Both tabs now update properly

2023-11-24 21:02 UTC, nikkikapadia approved these changes
approved for functionality but take a look at the comments

2023-11-24 21:02 UTC, nikkikapadia commented on launchpad-frontend/src/jobsPage/jobsPage.js
> +  /*const [save, setSave] = React.useState(
take out commented code plz

2023-11-24 21:02 UTC, nikkikapadia commented on launchpad-frontend/src/jobsPage/jobsPage.js
> +    //expandedPosting.saved = !save;
comments again

2023-11-26 22:50 UTC, merged